name: flutter_referral_link
description: "Empower your network with referral links, effortlessly track referrals and incentivize engagement for mutual growth."
version: 1.0.0
repository: https://github.com/Mohiuddin655-PUB/flutter_referral_link.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_ip_address: ^0.0.6
  cloud_firestore: ^4.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter: